blank_issues_enabled: true
contact_links:
  - name: "💬 Telegram Сообщество Keenetic Smart-Utils"
    url: "https://t.me/KeeneticSmartUtils"
    about: "Обсуждение, оперативная помощь и общение с сообществом"
  - name: "🌐 Официальный форум Keenetic"
    url: "https://forum.keenetic.ru/topic/30698-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-smart-utils-smart-route-smart-photo-snakelair-keenetic-entware-opkg-repository/"
    about: "Тема обсуждения пакетов Smart-Utils, Smart-Route и Smart-Photo"
